version: '3.4'

services:
  hotelbooking:
    image: hotelbooking
    build:
      context: .
      dockerfile: HotelBooking/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5089
    ports:
      - '5089:5089'
